//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ппEntities : DbContext
    {
        public ппEntities()
            : base("name=ппEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Вид_документа> Вид_документа { get; set; }
        public virtual DbSet<гр_специальностей> гр_специальностей { get; set; }
        public virtual DbSet<Гражданство_код_> Гражданство_код_ { get; set; }
        public virtual DbSet<Документы> Документы { get; set; }
        public virtual DbSet<Доп_программа> Доп_программа { get; set; }
        public virtual DbSet<ДПО> ДПО { get; set; }
        public virtual DbSet<область_проф_деятельности> область_проф_деятельности { get; set; }
        public virtual DbSet<Обучающиеся> Обучающиеся { get; set; }
        public virtual DbSet<Подтверждение_обмена> Подтверждение_обмена { get; set; }
        public virtual DbSet<Подтверждение_уничтожения> Подтверждение_уничтожения { get; set; }
        public virtual DbSet<Подтверждение_утраты> Подтверждение_утраты { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Сдача_отчетности> Сдача_отчетности { get; set; }
        public virtual DbSet<Статус_документа> Статус_документа { get; set; }
        public virtual DbSet<Уровень_образования> Уровень_образования { get; set; }
        public virtual DbSet<Финансирования> Финансирования { get; set; }
        public virtual DbSet<Форма_обучения> Форма_обучения { get; set; }
        public virtual DbSet<Форма_получения_образования__на_момент_прекращения_образ_отношений> Форма_получения_образования__на_момент_прекращения_образ_отношений { get; set; }
    }
}
