//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int id { get; set; }
        public Nullable<int> Вид_документа { get; set; }
        public Nullable<int> Статус_документа { get; set; }
        public Nullable<int> Подтверждение_утраты { get; set; }
        public Nullable<int> Подтверждение_обмена { get; set; }
        public Nullable<int> Подтверждение_уничтожения { get; set; }
        public Nullable<int> Серия_докумета { get; set; }
        public string Номер_документа { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public string Регист_номер { get; set; }
        public Nullable<int> Доп_программа { get; set; }
    
        public virtual Вид_документа Вид_документа1 { get; set; }
        public virtual Доп_программа Доп_программа1 { get; set; }
        public virtual Подтверждение_обмена Подтверждение_обмена1 { get; set; }
        public virtual Подтверждение_уничтожения Подтверждение_уничтожения1 { get; set; }
        public virtual Подтверждение_утраты Подтверждение_утраты1 { get; set; }
        public virtual Статус_документа Статус_документа1 { get; set; }
    }
}
