//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сдача_отчетности
    {
        public int id { get; set; }
        public Nullable<int> Гражданство { get; set; }
        public string Наименование_документа_об_образовании { get; set; }
        public Nullable<int> Серия { get; set; }
        public Nullable<int> Номер { get; set; }
        public Nullable<int> Регистрационный_N { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Номер_документа_для_изменения { get; set; }
    
        public virtual Гражданство_код_ Гражданство_код_ { get; set; }
    }
}
